---
# External dependencies

- src: geerlingguy.apache
  version: 3.2.0
- src: geerlingguy.apache-php-fpm
  version: 1.1.0
- src: geerlingguy.composer
  version: 1.9.0
- src: geerlingguy.drush
  version: 3.3.0
- src: geerlingguy.nodejs
  version: 6.0.0
- src: geerlingguy.php
  version: 4.8.0
